CI: turn on sonar
Signed-off-by: nabim777 <nabinalemagar019@gmail.com>

diff --git a/.github/workflows/checkRestroProject.yml b/.github/workflows/checkRestroProject.yml
--- a/.github/workflows/checkRestroProject.yml
+++ b/.github/workflows/checkRestroProject.yml
@@ -1,55 +1,55 @@
-name: Run-project
+# name: Run-project
 
-on:
-  push:
-    branches:
-      - master
-  pull_request:
-    branches:
-      - master
-  workflow_dispatch:
+# on:
+#   push:
+#     branches:
+#       - master
+#   pull_request:
+#     branches:
+#       - master
+#   workflow_dispatch:
 
-jobs:
-  run-Restro-project:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout repo code
-        uses: actions/checkout@v3
+# jobs:
+#   run-Restro-project:
+#     runs-on: ubuntu-latest
+#     steps:
+#       - name: Checkout repo code
+#         uses: actions/checkout@v3
 
-      - name: Set up node
-        uses: actions/setup-node@v3
-        with:
-          node-version: 20.x
+#       - name: Set up node
+#         uses: actions/setup-node@v3
+#         with:
+#           node-version: 20.x
       
-      - name: Install dependencies
-        run: |
-          npm ci
-          npx playwright install chromium
+#       - name: Install dependencies
+#         run: |
+#           npm ci
+#           npx playwright install chromium
 
-      - name: JS lint
-        run: |
-          npm run lint || (echo "Linting failed! Please run 'npm run lint:fix' to fix the errors." && exit 1)
+#       - name: JS lint
+#         run: |
+#           npm run lint || (echo "Linting failed! Please run 'npm run lint:fix' to fix the errors." && exit 1)
 
-      - name: Run the project
-        run: |
-          npm run serve &
-          npm run backend &
+#       - name: Run the project
+#         run: |
+#           npm run serve &
+#           npm run backend &
 
-      - name: Wait for services
-        run: |
-          sudo apt-get install wait-for-it -y
-          wait-for-it -h localhost -p 8080 -t 10
-          wait-for-it -h localhost -p 3000 -t 10
+#       - name: Wait for services
+#         run: |
+#           sudo apt-get install wait-for-it -y
+#           wait-for-it -h localhost -p 8080 -t 10
+#           wait-for-it -h localhost -p 3000 -t 10
 
-      - name: Run ui tests
-        id: test-ui
-        run: |
-          npm run test:e2e tests
+#       - name: Run ui tests
+#         id: test-ui
+#         run: |
+#           npm run test:e2e tests
 
-      - name: Upload trace results
-        if: ${{ failure() && steps.test-ui.conclusion == 'failure' }}
-        uses: actions/upload-artifact@v4
-        with:
-          path: |
-            trace-results/*.zip
-            retention-days: 30
+#       - name: Upload trace results
+#         if: ${{ failure() && steps.test-ui.conclusion == 'failure' }}
+#         uses: actions/upload-artifact@v4
+#         with:
+#           path: |
+#             trace-results/*.zip
+#             retention-days: 30
